[package]
name = "day1"
version = "0.1.0"
authors = ["Allen Geer <allen.geer@assurity.co.nz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.12"
